spring:
  config:
    activate:
      on-profile: local
  datasource:
    url: jdbc:postgresql://localhost:25432/postgres
    hikari:
      username: postgres
      password: 1234

log:
  config:
    path: ./logs
    fileName: vrss-api
    errFileName: vrss-api-error
    historyLimitDays: 30
    errHistoryLimitDays: 90

api:
  svmp:
    baseUrl: https://svmp.seavantage.com
    authCode: ZGV2ZWxvcEBsaWZlbWVudG9ycy5jby5rcjpsaWZlbWVudG9yczIwQCM=

file:
  path: /Users/hyunjeeoh/data/